PaktolusApp/PaktolusApp/Controllers/HobbiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PaktolusApp.Interfaces.Services;
using PaktolusApp.Models;

namespace PaktolusApp.Controllers
{
    public class HobbiesController : Controller
    {
        //private readonly DbTestContext _context;
        private IHobbyService service;

        public HobbiesController(IHobbyService service)
        {
            this.service = service;
        }

        // GET: Hobbies
        public async Task<IActionResult> Index()
        {
            var hobbies = await this.service.GetAll();

            if (hobbies == null) Problem("No records found");

            return View(hobbies);
        }

        

        // GET: Hobbies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var hobby = await this.service.GetById(id??0);
            if (hobby == null) return NotFound();

            return View(hobby);
        }

        

        // GET: Hobbies/Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Active")] Hobby hobby)
        {
            if (ModelState.IsValid)
            {
                await this.service.Add(hobby); 
                return RedirectToAction(nameof(Index));
            }

            return View(hobby);
        }


        // GET: Hobbies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var hobby = await this.service.GetById(id ?? 0);
            if (hobby == null) return NotFound();
            return View(hobby);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Active")] Hobby hobby)
        {
            if (id != hobby.Id) return NotFound();

            try
            {
                if (ModelState.IsValid)
                {
                    await this.service.Update(hobby);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            
            return View(hobby);
        }

        
        // GET: Hobbies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var hobby = this.service.GetById(id ?? 0);
            if (hobby == null) return NotFound();
            return View(hobby.Result);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hobby = await this.service.GetById(id);
            if (hobby == null) return NotFound();
            await this.service.Delete(id);            
            return RedirectToAction(nameof(Index));
        }
        
    }

}

PaktolusApp/PaktolusApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PaktolusApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PaktolusApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PaktolusApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hobbies" asp-action="Index">Hobbies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PaktolusApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>